server:
  bind_address: "0.0.0.0"
  auth_port: 1812
  acct_port: 1813
  max_clients: 1000
  request_timeout: 30

logging:
  level: "debug"
  file: null

clients:
  - name: "test-nas"
    ip_address: "127.0.0.1"
    shared_secret: "testing123"
    nas_type: "other"
    enabled: true
  - name: "SATHQ-GST-AP4020"
    ip_address: "10.76.200.104"
    shared_secret: "notyrs2no"
    nas_type: "other"
    enabled: true
  - name: "SATHQ-LRM-AP4K"
    ip_address: "10.76.200.100"
    shared_secret: "notyrs2no"
    nas_type: "ap"
    enabled: true
  - name: "SATHQ-OBRM-AP4K"
    ip_address: "10.76.200.101"
    shared_secret: "notyrs2no"
    nas_type: "ap"
    enabled: true
